---
abstract: 'SQL DDL transformations and more'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Basename: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.6
  YAML: 0.66
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.98'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Translator
no_index:
  directory:
    - inc
    - share
    - t
recommends:
  GD: 0
  Graph::Directed: 0
  GraphViz: 0
  Spreadsheet::ParseExcel: 0.41
  Template: 2.2
  Text::ParseWords: 0
  Text::RecordParser: 0.02
  XML::LibXML: 1.69
requires:
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Class::Base: 0
  Class::Data::Inheritable: 0.02
  Class::MakeMethods: 0
  DBI: 0
  Digest::SHA1: 2
  ExtUtils::MakeMaker: 6.11
  File::Basename: 0
  File::ShareDir: 1
  File::Spec: 0
  IO::Dir: 0
  IO::Scalar: 2.11
  Parse::RecDescent: 1.962002
  Pod::Usage: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.6
  XML::Writer: 0.5
  YAML: 0.66
  perl: 5.005
resources:
  Ratings: http://cpanratings.perl.org/d/SQL-Translator
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SQL-Translator
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://sqlfairy.svn.sourceforge.net/svnroot/sqlfairy
version: 0.11006
